[server]
host = 0.0.0.0
port = 5001

[paths]
# Chemin absolu vers le dossier variac_control
app_dir = /Users/remirodriguez/Documents/CESI/A4/MI/Travail/variac_control

[arduino]
baudrate = 9600
timeout = 2

[pid]
p = 1.2
i = 0.05
d = 0.0
bangbang_threshold = 20

[sensor_1]
name = Sensor A — Low range
min_temp = 0
max_temp = 400
format = csv

[sensor_2]
name = Sensor B — High range
min_temp = 300
max_temp = 800
format = csv
