[server]
host = 0.0.0.0
port = 5001

[paths]
# Mac   : /Users/remirodriguez/Documents/CESI/A4/MI/Travail/variac_control
# Win   : C:\Users\Rahul.Samyal\Documents\variac_control
app_dir = /Users/remirodriguez/Documents/CESI/A4/MI/Travail/variac_control

[arduino]
# port = COM5
baudrate = 9600
timeout = 2

[pid]
p = 1.2
i = 0.05
d = 0.0
bangbang_threshold = 20

[sensor_1]
name = Sensor A — Low range
min_temp = 0
max_temp = 800
format = csv

[sensor_2]
name = Sensor B — High range
min_temp = 250
max_temp = 1500
format = csv

[sensor_csv]
csv_dir_1 = C:\Users\Rahul.Samyal\OneDrive - University of Limerick\Research\Documents\CalexConfig log files
csv_dir_2 = C:\Users\Rahul.Samyal\OneDrive - University of Limerick\Research\Documents\Optais log files
column_1 = 3
column_2 = 3
